version: '3'
services:
#    one_way_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_one_way_linked_list:/src/one_way_linked_list
#        working_dir: /src/one_way_linked_list
#        command: ./build.sh
#    doubly_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_doubly_linked_list:/src/doubly_linked_list
#        working_dir: /src/doubly_linked_list
#        command: ./build.sh
#    stack_array:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_stack_array:/src/stack_array
#        working_dir: /src/stack_array
#        command: ./build.sh
#    stack_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_stack_linked_list:/src/stack_linked_list
#        working_dir: /src/stack_linked_list
#        command: ./build.sh
#    queue_array:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_queue_array:/src/queue_array
#        working_dir: /src/queue_array
#        command: ./build.sh
#    queue_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#           - ./2020_queue_linked_list:/src/queue_linked_list
#        working_dir: /src/queue_linked_list
#        command: ./build.sh
#    selection_sort:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_selection_sort:/src/selection_sort
#        working_dir: /src/selection_sort
#        command: ./build.sh
#    quick_sort:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_quick_sort:/src/quick_sort
#        working_dir: /src/quick_sort
#        command: ./build.sh
#    insertion_sort:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_insertion_sort:/src/insertion_sort
#        working_dir: /src/insertion_sort
#        command: ./build.sh
#    counting_sort:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_counting_sort:/src/counting_sort
#        working_dir: /src/counting_sort
#        command: ./build.sh
#    radix_sort:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_radix_sort:/src/radix_sort
#        working_dir: /src/radix_sort
#        command: ./build.sh
#    binary_tree:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_binary_tree:/src/binary_tree
#        working_dir: /src/binary_tree
#        command: ./build.sh
#    priority_queue:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2021_priority_queue:/src/priority_queue
#        working_dir: /src/priority_queue
#        command: ./build.sh
    sequential_search:
        image: 'gcc:9.2'
        volumes:
            - ./2021_sequential_search:/src/sequential_search
        working_dir: /src/sequential_search
        command: ./build.sh