version: '3'
services:
#    one_way_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_one_way_linked_list:/src/one_way_linked_list
#        working_dir: /src/one_way_linked_list
#        command: ./build.sh
#    doubly_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_doubly_linked_list:/src/doubly_linked_list
#        working_dir: /src/doubly_linked_list
#        command: ./build.sh
#    stack_array:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_stack_array:/src/stack_array
#        working_dir: /src/stack_array
#        command: ./build.sh
#    stack_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_stack_linked_list:/src/stack_linked_list
#        working_dir: /src/stack_linked_list
#        command: ./build.sh
#    queue_array:
#        image: 'gcc:9.2'
#        volumes:
#            - ./2020_queue_array:/src/queue_array
#        working_dir: /src/queue_array
#        command: ./build.sh
#    queue_linked_list:
#        image: 'gcc:9.2'
#        volumes:
#           - ./2020_queue_linked_list:/src/queue_linked_list
#        working_dir: /src/queue_linked_list
#        command: ./build.sh
    selection_sort:
        image: 'gcc:9.2'
        volumes:
            - ./2021_selection_sort:/src/selection_sort
        working_dir: /src/selection_sort
        command: ./build.sh